### ISSUE TITLE
Speed up subclass of FreeSpaceLossModel by caching Weibull parameters

### ISSUE THREAD

**Issue by timcp** [matteoschiav/netsquid-freespace#2]
If a `FreeSpaceLossModel` is called, a loss probability is sampled from a Weibull distribution which depends on the length of the channel to which the loss model is attached. In the common scenario where the length of the channel is not changed during simulation, this implies that the same Weibull distribution parameters are recomputed every time the loss model is called.

We propose to make this faster by caching the Weibull distribution parameters. Specifically, to make a function which turns a (subclass of) `FreeSpaceLossModel` into a subclassed version of it which has a cache.

**Comment by matteoschiav** [comment]
This could be a good solution. Did you try to see if there is a computational advantage in using the cached version?

Since this version is not conflicting with the existing code, I think that we could include it by merging your branch into the main. What do you think?

**Comment by timcp** [comment]
Ideally, we should add some unit test, but otherwise it should be good to merge.

I did some exploratory simulations which indicate that the runtime advantage is very small.... (which is not so strange since the caching only skips evaluating a few formulas, which should be quite fast anyway).

I leave it up to you, @matteoschiav , as snippet maintainer, whether you want this in the master branch.
